version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=Asia/Tokyo
        - APP_ENV=${APP_ENV}
    ports:
      - ${COMPOSE_APP_PORT}:8000
    volumes:
      - .:/work
      - ./docker/ash:/etc/profile.d
      - ./storage/logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - TZ=Asia/Tokyo

  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - ${COMPOSE_WEB_PORT}:80
    volumes:
      - .:/work
      - ./storage/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo
      - PHP_IDE_CONFIG=serverName=${APP_NAME}

  db:
    image: mysql:8.0
    volumes:
      - ./storage/db:/var/lib/mysql
      - ./storage/logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - ${COMPOSE_DB_PORT}:3306

  db-testing:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    tmpfs:
      - /var/lib/mysql:uid=999,gid=999
      - /var/log/mysql:uid=999,gid=999
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - ${COMPOSE_TEST_DB_PORT}:3306

  node:
    image: node:12.8-alpine
    tty: true
    volumes:
      - .:/work
    working_dir: /work

  redis:
    image: redis:5.0-alpine
    volumes:
      - ./storage/redis:/data
    ports:
      - ${COMPOSE_REDIS_PORT}:6379

  mail:
    image: mailhog/mailhog
    ports:
      - ${COMPOSE_MAILHOG_PORT}:8025
